# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestC
  pod 'TestA', :path => '../TestA'
  pod 'TestB', :path => '../TestB'

  target 'TestCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
