# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestA
  pod 'AliyunPlayer_iOS/AliyunVodPlayerSDK'

  target 'TestATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
